: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX ICa_HVA
    USEION ca WRITE ica
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 1e-05 (S/cm2)
    e = 50.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ica (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ica = g * ( var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = (-0.055*v - 1.485)/(((-0.055*v - 1.485)/(exp(-0.263157894736842*v - 7.10526315789474) - 1.0) + 0.94*exp(-0.0588235294117647*v - 4.41176470588235))*(exp(-0.263157894736842*v - 7.10526315789474) - 1.0))
    tau0 = 1.0/((-0.055*v - 1.485)/(exp(-0.263157894736842*v - 7.10526315789474) - 1.0) + 0.94*exp(-0.0588235294117647*v - 4.41176470588235))
    var1inf = 0.000457*exp(-0.02*v - 0.26)/(0.000457*exp(-0.02*v - 0.26) + 0.0065/(exp(-0.0357142857142857*v - 0.535714285714286) + 1.0))
    tau1 = 1.0/(0.000457*exp(-0.02*v - 0.26) + 0.0065/(exp(-0.0357142857142857*v - 0.535714285714286) + 1.0))
}

