: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX ICa_LVA
    USEION ca WRITE ica
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 1e-05 (S/cm2)
    e = 50.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ica (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ica = g * ( var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = 1.0/(exp(-0.166666666666667*v - 6.66666666666667) + 1.0)
    tau0 = 1.69491525423729 + 6.77966101694915/(exp(0.2*v + 7.0) + 1.0)
    var1inf = 1.0/(exp(0.15625*v + 14.0625) + 1.0)
    tau1 = 6.77966101694915 + 16.9491525423729/(exp(0.142857142857143*v + 7.14285714285714) + 1.0)
}

