: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX Ih_HAY
    NONSPECIFIC_CURRENT i
    RANGE  g, e
    GLOBAL var0inf, tau0
    THREADSAFE
}

PARAMETER {
    g = 3.8e-06 (S/cm2)
    e = -45.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    i (mA/cm2)
    var0inf
    tau0 (ms)
    v (mV)
}

STATE {
    var0
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    i = g * ( var0 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
}

PROCEDURE rates(v) {
    var0inf = (0.00643*v + 0.996007)/(((0.00643*v + 0.996007)/(exp(0.0840336134453781*v + 13.0168067226891) - 1.0) + 0.193*exp(0.0302114803625378*v))*(exp(0.0840336134453781*v + 13.0168067226891) - 1.0))
    tau0 = 1.0/((0.00643*v + 0.996007)/(exp(0.0840336134453781*v + 13.0168067226891) - 1.0) + 0.193*exp(0.0302114803625378*v))
}

