: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX IK
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL var0inf, tau0
    THREADSAFE
}

PARAMETER {
    g = 0.036 (S/cm2)
    e = -77.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    var0inf
    tau0 (ms)
    v (mV)
}

STATE {
    var0
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * ( var0 * var0 * var0 * var0 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
}

PROCEDURE rates(v) {
    var0inf = (-0.01*v - 0.55)/(((-0.01*v - 0.55)/(exp(-0.1*v - 5.5) - 1.0) + 0.125*exp(-0.0125*v - 0.8125))*(exp(-0.1*v - 5.5) - 1.0))
    tau0 = 1.0/(1.0*(-0.01*v - 0.55)/(exp(-0.1*v - 5.5) - 1.0) + 0.125*exp(-0.0125*v - 0.8125))
}

