: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX IKA
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.0477 (S/cm2)
    e = -75.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * ( var0 * var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = pow(0.0761*exp(0.0314*v + 2.958508)/(exp(0.0346*v + 0.040482) + 1.0), 0.333333333333333)
    tau0 = 0.3632 + 1.158/(exp(0.0497*v + 2.781212) + 1.0)
    var1inf = 1.0/pow(exp(0.0688*v + 3.66704) + 1.0, 4)
    tau1 = 1.24 + 2.678/(exp(0.0624*v + 3.12) + 1.0)
}

