: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX IKlva
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.001 (S/cm2)
    e = -106.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * ( var0 * var0 * var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = 1.0/(exp(-0.0854700854700855*v - 4.9008547008547) + 1.0)
    tau0 = 0.35 + 21.5/(24.0*exp(-0.0197628458498024*v - 1.18577075098814) + 6.0*exp(0.142857142857143*v + 8.57142857142857))
    var1inf = 0.27 + 0.73/(exp(0.162337662337662*v + 10.8766233766234) + 1.0)
    tau1 = 10.7 + 170.0/(exp(-0.125*v - 8.75) + 5.0*exp(0.1*v + 6.0))
}

