: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX IKpst
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.001 (S/cm2)
    e = -106.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * ( var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = 1.0/(exp(-0.0833333333333333*v - 0.916666666666667) + 1.0)
    tau0 = 1.03050847457627 + 5.86440677966102*exp(-pow(0.0628930817610063*v + 3.77358490566038, 2)) + 8.54237288135593*exp(-pow(0.0174216027874564*v + 1.04529616724739, 2))
    var1inf = 1.0/(exp(0.0909090909090909*v + 5.81818181818182) + 1.0)
    tau1 = 0.338983050847458*(24.0*v + 2570.0)*exp(-pow(0.0208333333333333*v + 1.77083333333333, 2)) + 122.033898305085
}

