: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX Im
    USEION k WRITE ik
    RANGE  g, e
    GLOBAL var0inf, tau0
    THREADSAFE
}

PARAMETER {
    g = 3.8e-06 (S/cm2)
    e = -80.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    var0inf
    tau0 (ms)
    v (mV)
}

STATE {
    var0
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * ( var0 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
}

PROCEDURE rates(v) {
    var0inf = 0.0033*exp(0.1*v + 3.5)/(0.0033*exp(-0.1*v - 3.5) + 0.0033*exp(0.1*v + 3.5))
    tau0 = 0.338983050847458/(0.0033*exp(-0.1*v - 3.5) + 0.0033*exp(0.1*v + 3.5))
}

