: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX INa_p
    USEION na WRITE ina
    RANGE  g, e
    GLOBAL var0inf, var1inf, tau0, tau1
    THREADSAFE
}

PARAMETER {
    g = 0.12 (S/cm2)
    e = 50.0 (mV)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ina (mA/cm2)
    var0inf
    tau0 (ms)
    var1inf
    tau1 (ms)
    v (mV)
}

STATE {
    var0
    var1
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ina = g * ( var0 * var0 * var0 * var1 *1.0) * (v - e)
}

INITIAL {
    rates(v)
    var0 = var0inf
    var1 = var1inf
}

DERIVATIVE states {
    rates(v)
    var0' = (var0inf - var0) / tau0
    var1' = (var1inf - var1) / tau1
}

PROCEDURE rates(v) {
    var0inf = 1.0/(exp(-0.217391304347826*v - 11.4347826086957) + 1.0)
    tau0 = 2.03389830508475/((-0.124*v - 4.712)/(-exp(0.166666666666667*v + 6.33333333333333) + 1.0) + (0.182*v + 6.916)/(-exp(-0.166666666666667*v - 6.33333333333333) + 1.0))
    var1inf = 1.0/(exp(0.1*v + 4.88) + 1.0)
    tau1 = 0.338983050847458/((-2.88e-6*v - 4.896e-5)/(-exp(0.215982721382289*v + 3.67170626349892) + 1.0) + (6.94e-6*v + 0.000446936)/(-exp(-0.380228136882129*v - 24.4866920152091) + 1.0))
}

