: This mod file is automaticaly generated by the ionc.write_mode_file() function in /source/ionchannels.py 

NEURON {
    SUFFIX ISK
    USEION k WRITE ik
    USEION ca READ cai
    RANGE  g, e
    GLOBAL var0inf, tau0
    THREADSAFE
}

PARAMETER {
    g = 1e-05 (S/cm2)
    e = -80 (mV)
    cai (mM)
}

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (mM) = (milli/liter)
}

ASSIGNED {
    ik (mA/cm2)
    var0inf
    tau0 (ms)
    v (mV)
}

STATE {
    var0
}

BREAKPOINT {
    SOLVE states METHOD cnexp
    ik = g * ( var0 *1.0) * (v - e)
}

INITIAL {
    rates(v, cai)
    var0 = var0inf
}

DERIVATIVE states {
    rates(v, cai)
    var0' = (var0inf - var0) / tau0
}

PROCEDURE rates(v, ca) {
    var0inf = 1.0/(pow(0.00043/ca, 4.8) + 1.0)
    tau0 = 1.00000000000000
}

